server {
    listen 80;
    server_name university.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name univ.demo.local;

    ssl_certificate /etc/nginx/ssl/university.crt;
    ssl_certificate_key /etc/nginx/ssl/university.key;

    location / {
        proxy_pass http://react-frontend:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api {
        proxy_pass http://go-backend:8080;
    }
}